updated ci file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,23 +6,36 @@ on:
       - main
 jobs:
   build-and-test:
-    runs-on: macos-14
+    runs-on: macos-latest
+    
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
-      - name: Set up Xcode version
-        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
-      - name: Show current version of Xcode
-        run: xcodebuild -version
+        uses: actions/checkout@v4
+        
+      - name: Create test results directory
+        run: mkdir -p TestResults
+        
+      - name: Set up simulator
+        run: xcrun simctl boot "iPhone 15" || true
+        
       - name: Build and Test
         uses: sersoft-gmbh/xcodebuild-action@v3.2.0
         with:
           project: EPCollaboratif.xcodeproj
           scheme: EPCollaboratif
-          destination: platform=iOS Simulator,name=iPhone 15
+          destination: 'platform=iOS Simulator,name=iPhone 15'
           action: test
-          build-settings: CODE_SIGNING_ALLOWED='NO'
-          result-bundle-path: TestResults/TestResults.xcresult
+          result-bundle-path: 'TestResults/TestResults.xcresult'
+          
+      - name: Check if Test Results Exist
+        run: |
+          if [ -d "testResults/TestResults.xcresult" ]; then
+            echo "Test results found."
+          else
+            echo "Test results not found."
+            exit 1
+          fi
+          
       - name: Process Test Results
         uses: kishikawakatsumi/xcresulttool@v1
         with:
